services:
  web:
    container_name: eventosweb
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ../app:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api
    networks:
      - mynetwork
  api:
    container_name: eventosapi
    build: ../app-php/.
    ports: 
      - "8082:80"
    depends_on:
      - db
    networks:
      - mynetwork
  db:
    container_name: eventosdb
    image: mysql:5.7
    restart: always
    volumes:
      - "../sql/baseicial.sql:/docker-entrypoint-initdb.d/start.sql"
      - ../mysqldata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: eventos
      MYSQL_DATABASE: eventos
      MYSQL_USER: eventos
      MYSQL_PASSWORD: eventos
    ports:
      - "3306:3306"
    networks:
      - mynetwork
  phpmyadmin:
    container_name: eventosphpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: eventosdb
      MYSQL_ROOT_PASSWORD: root
    networks:
      - mynetwork
networks: 
  mynetwork:
    driver: bridge
